# Pipeline that builds and pushes the microsoft/mlopspython image.
resources:
- repo: self

pool: 
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
    - master

  paths:
    include:
    - Python/azureml-pipeline-databricks/environment_setup/Dockerfile

variables:
  containerRegistry: $[coalesce(variables['acrServiceConnection'], 'acrconnection')]
  imageName: $[coalesce(variables['agentImageName'], 'azureml-pipeline-databricks')]  

steps:
  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageName)'
      tags: |
       $(Build.BuildNumber)
       latest
      buildContext: Python/azureml-pipeline-databricks
      dockerFile: environment_setup/Dockerfile
