pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/

variables:
- group: terraform
- group: ml-infrastructure

pool:
  vmImage: ubuntu-latest

jobs:
- template: terraform/terraform-job-template.yml
  parameters:
    environment: test

- job: Post_terraform
  dependsOn: Terraform
  variables:
    resource_group_name: $[ dependencies.Terraform.outputs['Terraform.TerraformOutputs.resource_group_name'] ]
    aml_workspace_name: $[ dependencies.Terraform.outputs['Terraform.TerraformOutputs.aml_workspace_name'] ]
    DATABRICKS_REGION: $[ dependencies.Terraform.outputs['Terraform.TerraformOutputs.databricks_region'] ]
  steps:
    - task: AzureCLI@1
      displayName: Build train pipeline
      inputs:
        azureSubscription: DataOpsML Azure DevOps ML Model CI/CD pipeline
        scriptLocation: inlineScript
        inlineScript: |
          python -m ml_service.pipelines.build_train_pipeline
